version: '3.8'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - book-network

  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - book-network

volumes:
  postgres_data:

networks:
  book-network:
    driver: bridge
